```{r}
library(tidyverse)
```
```{r}
data <- read_csv("data/data_csv.csv", n_max = 10)
data
```
```{r}
read_rds("data/data_rds.rds")
write_rds(data, "out/data_rds.rds")
```
```{r}




library(tidyverse)
library(flextable)



```
```{r}
data <- read_tsv("data/data_tsv.tsv", show_col_types = FALSE)
data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(
  data$`Группа крови`,
  levels = c("O (I)", "A (II)", "B (III)", "AB (IV)")
)
```
```{r}
statistics <- list(
  `Количество субъектов` = ~ length(.x),
  `Количество (есть данные)` = ~ sum(!is.na(.x)),
  `Нет данных` = ~ sum(is.na(.x)),
  `Ср. знач.` = ~ mean(.x, na.rm = TRUE),
  `Станд. отклон.` = ~ sd(.x, na.rm = TRUE),
  `мин.` = ~ min(.x, na.rm = TRUE),
  `макс.` = ~ max(.x, na.rm = TRUE),
  `Медиана` = ~ median(.x, na.rm = TRUE),
  `Q1` = ~ quantile(.x, 0.25, na.rm = TRUE),
  `Q3` = ~ quantile(.x, 0.75, na.rm = TRUE)
)
```
```{r}
table <- data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), statistics, .names = "{.col}__{.fn}")) |>
  mutate(across(-`Группа`, function(x) round(x, 2))) |>
  mutate(across(-`Группа`, as.character)) |>
  mutate(across(-`Группа`, function(x) replace_na(x, "Н/П*"))) |>
  pivot_longer(!`Группа`) |>
  separate(name, into = c("Переменная", "Статистика"), sep = "__") |>
  rename(`Значение` = value)
```
```{r}
table |>
  flextable() |>
   theme_box() |>
  merge_v(c("Группа", "Переменная"))
```
```{r}
tibble(var_1 = c("p-value", "0.001"),
       var_2 = c("p-value", "0.05")) |>
  flextable() |>
  theme_box() |>
  merge_h(i = 1)
```
```{r}
table <- tibble(
    `Adverse events` = c("SOC Желудочно-кишечные нарушения 10017947",
    "PT Тошнота 10028813",
    "PT Головная боль 10019211"
  )
)
```
```{r}
table |>
  flextable() |>
  theme_box() |>
  align(align = "center", part = "all")
```
```{r}
table |>
  flextable() |>
  theme_box() |>
  align(i = ~ str_detect(`Adverse events`, "SOC"), align = "left") |>
  align(i = ~ str_detect(`Adverse events`, "PT"), align = "right") |>
  width(width = 2)
```
```{r}
table |>
  flextable() |>
  theme_box() |>
  align(i = ~ str_detect(`Adverse events`, "SOC"), align = "left") |>
  align(i = ~ str_detect(`Adverse events`, "PT"), align = "right") |>
  bold(i = ~ str_detect(`Adverse events`, "SOC")) |>
  italic(i = ~ str_detect(`Adverse events`, "PT")) |>
  width(width = 2)
```
```{r}
is_pvalue_sign <- function(x) {
  as.numeric(str_remove(x, "<")) <= 0.05
}
```
```{r}
table <- tibble("p-value" = c("<0.001", "0.38", "0.124", "0.005", "0.05"))
```
```{r}
table |>
  flextable() |>
  theme_box() |>
  color(i = ~ is_pvalue_sign(`p-value`), color = "orange")
```
```{r}
table |>
  flextable() |>
  theme_box() |>
  bg(i = ~ is_pvalue_sign(`p-value`), bg = "orange")
```